### ISSUE TITLE
It's not an issue it's just a suggestion..

### ISSUE THREAD

**Issue by nabeelomer** [Olster/HTTPParser#2]
You could change the file main.cpp to parser.h and you can change the method `main()` in main.cpp to `parse(std::string request)` and it would be easier to use and one can just include the file in their code.

**Comment by Olster** [comment]
Thank you for the suggestion. This is a work in progress and I'm testing things out, so I'm not putting it in separate files for now.
And if I were to make a ```parse()``` function, the signature would be ```parse(const std::string& request)``` to avoid copying.
