### ISSUE TITLE
It Doesn't Work...

### ISSUE THREAD

**Issue by nabeelomer** [Olster/HTTPParser#3]
Hi,
I'm back,
The new parser base doesn't work, I tried to use it in my server but it doesn't parse anything.

```C++
   StringPiece method;
    StringPiece url;
    StringPiece http;
//all three of them are blank...
```
It doesn't even parse the request that you include in it....

**Comment by Olster** [comment]
No issue on my side. Debug your code and report an actual error if you find it.
![screen](https://cloud.githubusercontent.com/assets/2219064/7323154/4cffb11c-eab5-11e4-871c-4c419a23d153.png)

**Comment by Olster** [comment]
Also keep in mind that it's a work in progress and it it won't parse all requests.

**Comment by nabeelomer** [comment]
Ok yes it was my mistake. But its good to clear your doubts. And one more thing why do so much to parse requests why not just split the whole thing and add it to a vector? Is it something to do with performance?

**Comment by Olster** [comment]
// Your comment doesn't show up in the list, but id does in notifications.
You could just use string stream to get the data you need...
State machine is more memory efficient.

**Comment by nabeelomer** [comment]
Is https://github.com/nabeelomer/Light-HTTP-Parser memory inefficient?

**Comment by Olster** [comment]
It's not because of the amount of internal memory allocations.
But it's a working solution as well.
```n ss(*request);``` One full copy.
```tokens.push_back(buf);``` A new string is created for all request parts.
And what if your request is messed up or not an HTTP request at all?

e.g. NOT
```
GET / HTTP/1.1
...
```
BUT:
```
ASDSDAASADASDASDASDASD
...
```
Then the code you sent would crash at ```.at(n)```

**Comment by nabeelomer** [comment]
That is the purpose try and catch are serving...

**Comment by Olster** [comment]
Makes sense.
Closing this issue since the issue doesn't exist.
